# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Alethia < Formula
  desc "Alethia CLI for managing infrastructure configurations."
  homepage "https://github.com/alethialabs-io/alethia-cli"
  version "0.4.0"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alethialabs-io/alethia-cli/releases/download/v0.4.0/alethia_Darwin_x86_64.tar.gz"
      sha256 "f51788755bfece0ae6af74224bcf6eff8e97d1676bc805a4dfc0c7e426341c85"

      define_method(:install) do
        bin.install "alethia"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alethialabs-io/alethia-cli/releases/download/v0.4.0/alethia_Darwin_arm64.tar.gz"
      sha256 "93670679b4296e08b1b20d7d1c6681afa866cca8aa6ce86d55e0789ab1f6fb9d"

      define_method(:install) do
        bin.install "alethia"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alethialabs-io/alethia-cli/releases/download/v0.4.0/alethia_Linux_x86_64.tar.gz"
      sha256 "08e68e9355fc859a54da7d673ff18b05bb3f894dfadc5d0eba67dd25ab0054eb"
      define_method(:install) do
        bin.install "alethia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alethialabs-io/alethia-cli/releases/download/v0.4.0/alethia_Linux_arm64.tar.gz"
      sha256 "4dae12b0ad360d9560cbc7b84ecab23a1268ba5965ce84315d3461f2678a1e5d"
      define_method(:install) do
        bin.install "alethia"
      end
    end
  end

  test do
    system "#{bin}/alethia", "--version"
  end
end
