# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Alethia < Formula
  desc "Alethia CLI for managing infrastructure configurations."
  homepage "https://github.com/alethialabs-io/alethia-cli"
  version "0.7.0"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alethialabs-io/alethia-cli/releases/download/v0.7.0/alethia_Darwin_x86_64.tar.gz"
      sha256 "0de7875a0a27e790677a797ae4f8aa32dff620adbb645c098a75bd6eda9f7d50"

      define_method(:install) do
        bin.install "alethia"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alethialabs-io/alethia-cli/releases/download/v0.7.0/alethia_Darwin_arm64.tar.gz"
      sha256 "9fe55fe39a4dbe6ca64df72b20fc73c1173ca860e1325d8ea04c60c995ab78ea"

      define_method(:install) do
        bin.install "alethia"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alethialabs-io/alethia-cli/releases/download/v0.7.0/alethia_Linux_x86_64.tar.gz"
      sha256 "c13206c061410a2a9dc8eacf022a2863799d2e59f58cd317bc50866229033a58"
      define_method(:install) do
        bin.install "alethia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alethialabs-io/alethia-cli/releases/download/v0.7.0/alethia_Linux_arm64.tar.gz"
      sha256 "676a0b41c5aee661ae2faeb9ba6d817d4e61cc998bdd9b0796036637c310be1a"
      define_method(:install) do
        bin.install "alethia"
      end
    end
  end

  test do
    system "#{bin}/alethia", "--version"
  end
end
